name: Flutter CI
on:
  pull_request:
    branches: [ main]  # <-- VÉRIFIEZ L'ESPACE ICI !
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          # Utilise la dernière version stable.
          channel: 'stable' 
          # On peut aussi tenter une version spécifique récente si le 'stable' ne suffit pas
          # flutter-version: '3.22.3' 
      - name: Install dependencies
        # Ajout de l'option "--no-version-check" pour ignorer le conflit pubspec/Dart SDK
        run: flutter pub get --no-version-check 
      - name: Run tests
        run: flutter test
      - name: Analyze code
        run: flutter analyze